kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: perceptilabs-pvc
spec:
  storageClassName: STORAGE_CLASS
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
